// <auto-generated />
using System;
using FuFood.Data;
using FuFood.Models.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FuFood.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251227070859_AddUniqueConstraintToInventoryTransactionItems")]
    partial class AddUniqueConstraintToInventoryTransactionItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "product_unit", new[] { "件", "個", "公克", "公升", "公斤", "包", "塊", "壺", "把", "杯", "桶", "條", "毫克", "毫升", "片", "瓶", "盒", "箱", "粒", "罐", "袋", "袋裝", "顆" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FuFood.Models.Entities.InventoryTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RefrigeratorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FinalizedAt");

                    b.HasIndex("RefrigeratorId");

                    b.HasIndex("UserId");

                    b.ToTable("InventoryTransactions");
                });

            modelBuilder.Entity("FuFood.Models.Entities.InventoryTransactionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FullyConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InventoryTransactionId")
                        .HasColumnType("uuid");

                    b.Property<string>("InventoryTransactionItemImage")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FullyConsumedAt");

                    b.HasIndex("InventoryTransactionId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ParentId", "InventoryTransactionId")
                        .IsUnique()
                        .HasFilter("\"ParentId\" is not null");

                    b.ToTable("InventoryTransactionsItems", t =>
                        {
                            t.HasCheckConstraint("item_expiration_date_check", "\"ParentId\" is not null or \"ExpirationDate\" is not null");

                            t.HasCheckConstraint("item_quantity_sign_check", "(\"ParentId\" is null and \"Quantity\" > 0) or (\"ParentId\" is not null and \"Quantity\" < 0)");
                        });
                });

            modelBuilder.Entity("FuFood.Models.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Categories")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<UnitType>("Unit")
                        .HasColumnType("product_unit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("FuFood.Models.Entities.Refrigerator", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Colour")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById")
                        .IsUnique()
                        .HasFilter("\"IsDefault\" = true");

                    b.ToTable("Refrigerators");
                });

            modelBuilder.Entity("FuFood.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LineId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LineId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FuFood.Models.RevokedAccessToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("RevokedAccessTokens");
                });

            modelBuilder.Entity("FuFood.Models.Entities.InventoryTransaction", b =>
                {
                    b.HasOne("FuFood.Models.Entities.Refrigerator", "Refrigerator")
                        .WithMany()
                        .HasForeignKey("RefrigeratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuFood.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Refrigerator");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FuFood.Models.Entities.InventoryTransactionItem", b =>
                {
                    b.HasOne("FuFood.Models.Entities.InventoryTransaction", "InventoryTransaction")
                        .WithMany("Items")
                        .HasForeignKey("InventoryTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuFood.Models.Entities.InventoryTransactionItem", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.HasOne("FuFood.Models.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryTransaction");

                    b.Navigation("Parent");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FuFood.Models.Entities.Refrigerator", b =>
                {
                    b.HasOne("FuFood.Models.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("FuFood.Models.Entities.InventoryTransaction", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
